### ISSUE TITLE
One Piece Unlimited World Red Freeze on Startup with Tiramisu

### ISSUE THREAD

**Issue by mhoare1984** [wiiu-env/Tiramisu#15]
I have the actual disc copy (non pirated) and if I start the game with my Tiramisu home brew SD card in my Wii U on startup, the game will crash on the first loading screen. If I start my Wii U without the SD card in, i get the black screen about error booting Tiramisu, and then it boots the normal Wii U UI. If I start the game from the disc then it starts. I also dumped the game onto my external hard disk and did the same test with the same results. It seems this game does not like Tiramisu. Any ideas what might be going on?

**Comment by mhoare1984** [comment]
It is the EU PAL version of the game

**Comment by mhoare1984** [comment]
Mass Effect 3 PAL EU and Batman Arkham City Armoured Edition PAL EU also do the same thing

**Comment by Maschell** [comment]
Are you using the latest version of Tiramisu? At least Mass Effect 3 was fixed several months ago

**Comment by mhoare1984** [comment]
Quite possibly using an older version. The Wii U was second hand came with Tiramisu installed and it looks like it auto boots from the SD Card. What is the process for upgrading a Tiramisu install on a Wii U? Is it just a matter of updating files on the SD Card or will I need to remove Tiramisu and re-install it? I have been looking at the guide at https://wiiu.hacks.guide/#/introduction and it doesn't mention upgrading.

**Comment by Maschell** [comment]
Just download the latest files from https://tiramisu.foryour.cafe/ and replace the files on the sd card

**Comment by mhoare1984** [comment]
I loaded the latest version of Tiramisu onto the SD Card and also grabbed the latest signatures file too. Mass Effect 3 and Batman Arkham City now work. 

One Piece Unlimited World Red still fails to load. The opening screen shows (map of the world on the gamepad) but the Wii U is still playing the menu sound and it has hard locked. No buttons will respond. The power button needs to be held in until it turns off.

**Comment by Maschell** [comment]
Can you confirm ONE PIECE is booting when you replace `sd:/wiiu/environments/tiramisu/modules/setup/00_mocha.rpx` with [this one](https://github.com/wiiu-env/MochaPayload/suites/7258027877/artifacts/291774327)?

**Comment by mhoare1984** [comment]
Yep with that file in place, the game started and ran correctly

**Comment by mhoare1984** [comment]
A side effect of that file is that with the updated file Rayman Legends fails to start. I replaced the new 00_mocha.rpx file with the one that came with the latest version of Tiramisu and the game started without issue. But then One Piece didn't start again.

**Comment by Maschell** [comment]
Are you 100% sure about this? From my point of view it's impossible this would break Rayman Legends. It is a very small, ONE PIECE specific, patch that isn't applied for any other game

**Comment by mhoare1984** [comment]
I'm 100% sure. I was fairly certain Rayman Legends worked on the original old version of Tiramisu, plus the updated version I put on the SD Card. 

After placing the 00_mocha.rpx file from your "this one" link above, One Piece worked, and then I started testing all my other pal games to see if they still worked.

 I've tested almost half and so far only Rayman Legends failed to start. I thought maybe this game never worked so I restored 00_mocha.rpx  from the latest version of Tiramisu and tried to start the game, and it worked. I then placed in the "this one" linked above, and again the game did not start, freezing on the first screen, just like One Piece did.

I can record a video of this if you like?

**Comment by mhoare1984** [comment]
I recorded a video to show, I still had the new 00_mocha.rpx file on my SD Card just renamed 00_mocha.new. I did a checksum of that file and it matched the checksum of a freshly downloaded version from your link above. Put my SD Card back in the Wii U with the camera rolling, and guess what, the game started.

Twice this morning the game failed to start. It is working now with your updated 00_mocha.rpx. I can't explain it. Once could just be a glitch, but twice it failed to start.

[Checksums of the file](https://imgur.com/a/ubJ5cZg)

**Comment by mhoare1984** [comment]
Thanks for the help with this, appreciate it. I purchased this second hand Wii U so my young son can enjoy our original (legal) Wii U game collection without fear of little fingers damaging the original discs. Your Tiramisu project has made this possible..
